backend:
  name: github
  repo: ndnk0311/do_an_nhom_10  # Thay thế bằng tên repo của bạn
  branch: main  # Hoặc tên nhánh mà bạn đang sử dụng

media_folder: "images"  # Thư mục mặc định chứa hình ảnh tải lên
public_folder: "/images"  # Thư mục công khai cho hình ảnh

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }  # Sử dụng thư mục media mặc định
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image", media_folder: "ảnh", public_folder: "/ảnh" }  # Chỉ định thư mục ảnh
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Main Image", name: "main_image", widget: "image", media_folder: "ảnh", public_folder: "/ảnh" }  # Sử dụng thư mục ảnh
      - { label: "Gallery", name: "gallery", widget: "list", field: { label: "Image", name: "image", widget: "image", media_folder: "images", public_folder: "/images" } }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image from images", name: "image_images", widget: "image", media_folder: "images", public_folder: "/images" }  # Chỉ định thư mục images
      - { label: "Image from ảnh", name: "image_anh", widget: "image", media_folder: "ảnh", public_folder: "/ảnh" }  # Chỉ định thư mục ảnh
